// Generated by scripts/generate-index.ts from the module files. Do not edit by hand:
// add a module file, then run `pnpm generate`.
import { definePack } from '@spawnforge/core';
import defaults from './defaults.ts';
import bodyPlansBiped from './body-plans/biped.ts';
import bodyPlansHexapod from './body-plans/hexapod.ts';
import bodyPlansQuadruped from './body-plans/quadruped.ts';
import bodyPlansSerpent from './body-plans/serpent.ts';
import partsEarPointed from './parts/ear.pointed.ts';
import partsEyeBasic from './parts/eye.basic.ts';
import partsFootClaw from './parts/foot.claw.ts';
import partsHornCurved from './parts/horn.curved.ts';
import partsSpikesRow from './parts/spikes.row.ts';
import partsTeethRow from './parts/teeth.row.ts';
import patternsCountershade from './patterns/countershade.ts';
import patternsGrime from './patterns/grime.ts';
import patternsMottle from './patterns/mottle.ts';
import patternsScales from './patterns/scales.ts';
import patternsSpots from './patterns/spots.ts';
import patternsStripes from './patterns/stripes.ts';
import gaitsSlither from './gaits/slither.ts';
import gaitsTripod from './gaits/tripod.ts';
import gaitsTrot from './gaits/trot.ts';
import gaitsWalk from './gaits/walk.ts';
import actionsBite from './actions/bite.ts';
import actionsIdle from './actions/idle.ts';
import actionsLook from './actions/look.ts';
import actionsRoar from './actions/roar.ts';
import themesDemon from './themes/demon.ts';
import themesInsect from './themes/insect.ts';
import themesReptile from './themes/reptile.ts';
import statsRpg from './stats/rpg.ts';

/** The first pack: body plans, parts, patterns, gaits and actions for the proof of concept. */
export const basicPack = definePack({
  id: 'basic',
  modules: [
    bodyPlansBiped,
    bodyPlansHexapod,
    bodyPlansQuadruped,
    bodyPlansSerpent,
    partsEarPointed,
    partsEyeBasic,
    partsFootClaw,
    partsHornCurved,
    partsSpikesRow,
    partsTeethRow,
    patternsCountershade,
    patternsGrime,
    patternsMottle,
    patternsScales,
    patternsSpots,
    patternsStripes,
    gaitsSlither,
    gaitsTripod,
    gaitsTrot,
    gaitsWalk,
    actionsBite,
    actionsIdle,
    actionsLook,
    actionsRoar,
    themesDemon,
    themesInsect,
    themesReptile,
    statsRpg,
  ],
  defaults,
});
