import { definePack } from '@spawnforge/core';

/**
 * The first pack: body plans, parts, patterns, gaits and actions for the proof of concept.
 * Each module is one file; this index will be generated by a script once modules exist.
 */
export const basicPack = definePack({ id: 'basic', modules: [] });
