/**
 * Writes packages/modules/src/index.ts from the module files on disk, so adding a module is one
 * file. Run with `--check` to fail instead of writing when the index is stale (CI does this).
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const FOLDERS = ['body-plans', 'parts', 'patterns', 'gaits', 'actions', 'themes', 'stats'] as const;
const src = new URL('../src/', import.meta.url);

export function renderIndex(): string {
  const entries: { name: string; path: string }[] = [];
  for (const folder of FOLDERS) {
    let files: string[];
    try {
      files = readdirSync(new URL(`${folder}/`, src));
    } catch {
      continue;
    }
    for (const file of files.sort()) {
      if (!file.endsWith('.ts') || file.endsWith('.test.ts') || file.startsWith('_')) continue;
      const stem = file.slice(0, -3);
      const name = `${folder}-${stem}`
        .split(/[-.]/)
        .map((w, i) => (i === 0 ? w : w[0]?.toUpperCase() + w.slice(1)))
        .join('');
      entries.push({ name, path: `./${folder}/${file}` });
    }
  }
  return [
    '// Generated by scripts/generate-index.ts from the module files. Do not edit by hand:',
    '// add a module file, then run `pnpm generate`.',
    "import { definePack } from '@spawnforge/core';",
    "import defaults from './defaults.ts';",
    ...entries.map((e) => `import ${e.name} from '${e.path}';`),
    '',
    '/** The first pack: body plans, parts, patterns, gaits and actions for the proof of concept. */',
    'export const basicPack = definePack({',
    "  id: 'basic',",
    '  modules: [',
    ...entries.map((e) => `    ${e.name},`),
    '  ],',
    '  defaults,',
    '});',
    '',
  ].join('\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const target = new URL('index.ts', src);
  const next = renderIndex();
  const current = readFileSync(target, 'utf8');
  if (process.argv.includes('--check')) {
    if (current !== next) {
      console.error('packages/modules/src/index.ts is stale; run `pnpm generate`.');
      process.exit(1);
    }
  } else if (current !== next) {
    writeFileSync(target, next);
    console.log('wrote packages/modules/src/index.ts');
  }
}
