import { blueprintSchemaFor, FORMAT, MODULE_KINDS, type ModuleKind } from '@spawnforge/core';
import { z } from 'zod';
import { describeModule, getRegistry } from './commands.ts';
import { compactJson } from './json.ts';

const KIND_TITLES: Record<ModuleKind, string> = {
  bodyPlan: 'Body plans',
  part: 'Parts',
  pattern: 'Patterns',
  gait: 'Gaits',
  action: 'Actions',
  theme: 'Themes',
  stats: 'Stats',
};

interface JsonProp {
  type?: string;
  enum?: unknown[];
  minimum?: number;
  maximum?: number;
  default?: unknown;
  description?: string;
  anyOf?: JsonProp[];
  items?: JsonProp;
}

function typeOf(p: JsonProp): string {
  if (p.enum) return p.enum.map((v) => JSON.stringify(v)).join(' | ');
  if (p.anyOf) return p.anyOf.map(typeOf).join(' or ');
  if (p.type === 'array' && p.items) return `list of ${typeOf(p.items)}`;
  if (p.type === 'integer') return 'integer';
  return p.type ?? 'any';
}

function rangeOf(p: JsonProp): string {
  const src = p.anyOf?.find((o) => o.minimum !== undefined) ?? p;
  if (src.minimum !== undefined && src.maximum !== undefined)
    return `${src.minimum}–${src.maximum}`;
  if (src.minimum !== undefined) return `≥ ${src.minimum}`;
  if (src.maximum !== undefined) return `≤ ${src.maximum}`;
  return '';
}

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

/** docs/catalog.md: every module with its parameters, ranges, defaults and an example. */
export function renderCatalog(registry = getRegistry()): string {
  const lines: string[] = [
    '# Module catalogue',
    '',
    `<!-- Generated by \`pnpm generate\` from the registered modules. Do not edit by hand. -->`,
    '',
    `Every module available to \`${FORMAT}\` blueprints. Lengths are in torso lengths (multiples of`,
    "the blueprint's `scale`); angles are in degrees. Run `spawnforge describe-module <id>` or the",
    '`describe_module` tool for the same facts as JSON.',
    '',
  ];
  lines.push(...renderFields(registry));
  for (const kind of MODULE_KINDS) {
    const modules = registry.list(kind);
    if (modules.length === 0) continue;
    lines.push(`## ${KIND_TITLES[kind]}`, '');
    for (const module of modules) {
      const d = describeModule({ id: module.id, kind }, registry);
      lines.push(`### \`${module.id}\``, '', d.summary, '', d.usage, '');
      if (d.planned)
        lines.push(
          `**Not built yet** (plan milestone ${d.planned}): it validates, but compile skips it and warns \`not_built\`.`,
          '',
        );
      if (d.details) {
        const facts = Object.entries(d.details)
          .map(([k, v]) => `${k}: \`${JSON.stringify(v)}\``)
          .join(' · ');
        lines.push(facts, '');
      }
      const props = (d.params.properties ?? {}) as Record<string, JsonProp>;
      if (Object.keys(props).length > 0) {
        lines.push(
          '| Parameter | Type | Range | Default | Description |',
          '| --- | --- | --- | --- | --- |',
        );
        for (const [name, p] of Object.entries(props)) {
          const def = p.default === undefined ? '' : `\`${compactJson(p.default)}\``;
          lines.push(
            `| \`${name}\` | ${cell(typeOf(p))} | ${rangeOf(p)} | ${def} | ${cell(p.description ?? '')} |`,
          );
        }
        lines.push('');
      }
      if (d.preset) {
        const ids = [
          ...((d.preset.limbs as { id: string }[] | undefined) ?? []).map(
            (l) => `limb \`${l.id}\``,
          ),
          ...((d.preset.parts as { id: string }[] | undefined) ?? []).map(
            (p) => `part \`${p.id}\``,
          ),
        ];
        if (ids.length > 0) lines.push(`Ids you can override: ${ids.join(', ')}.`, '');
        lines.push(
          '<details><summary>Preset</summary>',
          '',
          '```json',
          compactJson(d.preset),
          '```',
          '',
          '</details>',
          '',
        );
      } else if (d.example !== undefined) {
        lines.push('```json', compactJson(d.example), '```', '');
      }
    }
  }
  return lines.join('\n');
}

interface JsonNode extends JsonProp {
  properties?: Record<string, JsonNode>;
  additionalProperties?: JsonNode | boolean;
  prefault?: unknown;
}

/** Follows anyOf/items to the object schema inside a property, if any. */
function objectIn(node: JsonNode | undefined): JsonNode | undefined {
  if (!node) return undefined;
  if (node.properties) return node;
  if (node.items) return objectIn(node.items);
  for (const option of node.anyOf ?? []) {
    const found = objectIn(option);
    if (found) return found;
  }
  return undefined;
}

/** The "Blueprint fields" section: every non-module field with its type, range and default. */
function renderFields(registry = getRegistry()): string[] {
  const schema = z.toJSONSchema(blueprintSchemaFor(registry), {
    io: 'input',
    unrepresentable: 'any',
  }) as JsonNode;
  const top = schema.properties ?? {};
  const body = objectIn(top.body)?.properties ?? {};
  const limb = objectIn(top.limbs);
  const part = objectIn(top.parts);
  const skin = objectIn(top.skin)?.properties ?? {};
  const sections: [string, JsonNode | undefined][] = [
    ['Top level', schema],
    ['body.torso', objectIn(body.torso)],
    ['body.neck', objectIn(body.neck)],
    ['body.head', objectIn(body.head)],
    ['body.tail', objectIn(body.tail)],
    ['limbs[]', limb],
    ['limbs[].attach', objectIn(limb?.properties?.attach)],
    ['parts[]', part],
    ['parts[].attach', objectIn(part?.properties?.attach)],
    ['skin', objectIn(top.skin)],
    ['skin.layers[] (every layer)', objectIn(skin.layers)],
    ['motion', objectIn(top.motion)],
  ];
  const out = [
    '## Blueprint fields',
    '',
    'Every field outside the modules, generated from the schema. Fields with a default may be left out.',
    '',
  ];
  for (const [title, node] of sections) {
    if (!node?.properties) continue;
    out.push(`### \`${title}\``, '');
    if (node.description) out.push(node.description, '');
    out.push('| Field | Type | Range | Default | Description |', '| --- | --- | --- | --- | --- |');
    for (const [name, p] of Object.entries(node.properties)) {
      if (
        title === 'Top level' &&
        ['body', 'limbs', 'parts', 'skin', 'motion'].includes(name) &&
        !p.description
      )
        continue;
      const nested = objectIn(p) && !['foot', 'palette'].includes(name);
      const type = nested && p.type !== 'array' ? 'object (below)' : typeOf(p);
      const def = p.default === undefined ? '' : `\`${compactJson(p.default)}\``;
      out.push(
        `| \`${name}\` | ${cell(type)} | ${rangeOf(p)} | ${def} | ${cell(p.description ?? '')} |`,
      );
    }
    out.push('');
  }
  return out;
}
